core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    path('edit-form-<int:id>/', views.edit_form, name='edit-form'),
    path('form-<int:id>/edit/', views.edit_form_page, name='edit-form-page'),
    path('delete-form-<int:id>/', views.delete_form, name='delete-form'),
    path('form-management/', views.form_management, name='form-management'),
    path('user/<str:user>/', views.user_poll, name='user-poll'),
    path('tags/', views.tags, name='tags'),
    path('tag/<slug:slug>/', views.tag, name='tag'),
    path('addq/', views.add_q, name="add_q"),
    path('add-a-form/', views.add_q_page, name='add_q_page'),
    path('comment-<int:id>/', views.comment, name='comment'),
    path('profile/', views.profile, name='profile'),
    path('change-password/', views.change_pass, name='change_pass'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.signout, name='logout'),
    path('login/', views.signin, name='login'),
    path('user-signing/', views.user_signing, name="user-signing"),
    path('pvote/<int:id>/', views.pvote, name='pvote'),
    path('nvote/<int:id>/', views.nvote, name='nvote'),
    path('form-<int:id>/', views.q_page, name='q_page'),
    path('index/', views.index, name='index'),
    path('', views.intro, name='intro'),
]

polls/models.py
from django.db import models
from django.utils import timezone
import datetime
from .jalali_date_conv import shamsiDate
from django.contrib.auth.models import User
from django.utils.text import slugify

# Create your models here.


class Tag(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)

    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        return '/tag/%s/' % slugify(self.slug)


class Question(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=250, verbose_name='Title')
    text = models.TextField(verbose_name='Description', blank=True, null=True)
    date = models.DateTimeField(default=timezone.now, verbose_name='Date', blank=True)
    date_created = models.DateTimeField(auto_now_add=timezone.now())
    date_modified = models.DateTimeField(auto_now=timezone.now())
    publish = models.BooleanField(default=True, verbose_name='Publish')
    p_text = models.CharField(max_length=200, default='موافقم', verbose_name='Positive choice text', blank=True, null=True)
    p_votes = models.IntegerField(default=0, verbose_name='Positive choice votes', blank=True, null=True)
    n_text = models.CharField(max_length=200, default='مخالفم', verbose_name='Negative choice text', blank=True, null=True)
    n_votes = models.IntegerField(default=0, verbose_name='Negative choice votes', blank=True, null=True)
    date_limit = models.BooleanField(default=False)
    start_date = models.DateTimeField(blank=True, null=True)
    end_date = models.DateTimeField(blank=True, null=True)
    tags = models.ManyToManyField(Tag)

    class Meta:
        ordering = ['-date_created']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return '/form-%s/' % self.id

    def jalali_date(self):
        gdate = self.date
        return shamsiDate(gdate.year, gdate.month, gdate.day)

    def p_percent(self):
        sum = self.p_votes + self.n_votes
        if self.p_votes == 0 and self.n_votes == 0:
            percent = 50
        if self.p_votes == 0:
            percent = 0
        else:
            percent = (self.p_votes * 100)/sum
        return percent

    def n_percent(self):
        sum = self.n_votes + self.p_votes
        if self.p_votes == 0 and self.n_votes == 0:
            percent = 50
        if self.n_votes == 0:
            percent = 0
        else:
            percent = (self.n_votes * 100)/sum
        return percent

    def date_limit_checker(self):
        if self.date_limit:
            if timezone.now() < self.start_date < self.end_date:
                return 0
            elif self.start_date < timezone.now() < self.end_date:
                return 1
            elif self.start_date < self.end_date < timezone.now():
                return 2
            else:
                return False
        else:
            return True

    def fa_start_date(self):
        gdate = self.start_date
        return shamsiDate(gdate.year, gdate.month, gdate.day)

    def fa_end_date(self):
        gdate = self.end_date
        return shamsiDate(gdate.year, gdate.month, gdate.day)

    def sum_votes(self):
        return self.p_votes + self.n_votes


class VoteHistory(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=timezone.now(), verbose_name='date')
    user = models.CharField(max_length=150, verbose_name='username')
    ip = models.CharField(max_length=50, verbose_name='voted ip')
    choice = models.CharField(max_length=50, verbose_name='choice')

    class Meta:
        ordering = ['-date']

    def __str__(self):
        return str(self.user) + ' ' + str(self.ip)


class Comments(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    text = models.TextField(blank=False, null=False)
    date = models.DateTimeField(auto_now_add=timezone.now())

    class Meta:
        ordering = ['-date']

    def __str__(self):
        return self.text

    def jalali_date(self):
        gdate = self.date
        return shamsiDate(gdate.year, gdate.month, gdate.day)

polls/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.http import Http404, HttpResponseRedirect
from .models import *
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from ipware import get_client_ip

# Create your views here.


def index(request):
    questions = Question.objects.all().filter(publish=True).order_by('-date')
    return render(request, 'polls/index.html', {
        'questions': questions,
        })


def q_page(request, id):
    ip_req = request.META.get('HTTP_X_FORWARDED_FOR', request.META.get('REMOTE_ADDR', '')).split(',')[0].strip()

    question = get_object_or_404(Question, pk=id)
    u = request.user
    vh = VoteHistory()
    if VoteHistory.objects.filter(question_id=question.id, ip=str(ip_req)) or VoteHistory.objects.filter(question_id=question.id, user=u.username):
        voted = True
    else:
        voted = False

    if u == question.user:
        user_is_same = True
    else:
        user_is_same = False

    if question.publish:
        return render(request, 'polls/q_page.html', {
            'question': question,
            'user_is_same': user_is_same,
            'voted': voted,
            })
    elif not question.publish and user_is_same:
        return render(request, 'polls/q_page.html', {
            'question': question,
            'user_is_same': user_is_same,
            'voted': voted,
            'not_pub_err': 'این فرم در وضعیت عدم انتشار است. در این حالت فرم شما به نمایش عموم در نمی آید وتنها خودتان میتوانید این فرم نظرسنجی را مشاهده کنید.',
            })
    else:
        return render(request, 'polls/404.html')


def pvote(request, id):
    ip_req = request.META.get('HTTP_X_FORWARDED_FOR', request.META.get('REMOTE_ADDR', '')).split(',')[0].strip()

    q = get_object_or_404(Question, pk=id)
    vh = VoteHistory()
    if VoteHistory.objects.filter(question_id=q.id, ip=str(ip_req)) or VoteHistory.objects.filter(question_id=q.id, user=request.user.username):
        voted = True
        return render(request, 'polls/q_page.html', {
                'question': q,
                'error': 'شما قبلا رای دادید.',
            })
    else:
        voted = False
    try:
        if q.date_limit_checker() == 1 and not voted:
            if request.POST:
                q.p_votes += 1

                vh.question = q
                vh.user = request.user.username
                vh.ip = str(ip_req)
                vh.choice = '+'

            else:
                return render(request, 'polls/q_page.html', {
                    'question': q,
                    'error': 'خطا در ثبت رای !',
                })
        elif q.date_limit_checker() == 0:
            return render(request, 'polls/q_page.html', {
                    'question': q,
                    'error': 'این نظر سنجی دارای محدودیت زمانی است و هنوز شروع نشده!',
                })
        elif q.date_limit_checker() == 2:
            return render(request, 'polls/q_page.html', {
                    'question': q,
                    'error': 'این نظرسنجی دارای محدودیت زمانی بوده و مهلت آن به اتمام رسیده است.',
                })
        else:
            return HttpResponseRedirect(reverse('polls:q_page', args=[id]))
    except:
        return render(request, 'polls/q_page.html', {
            'question': q,
            'error': 'خطا در ثبت رای !',
        })
    else:
        q.save()
        vh.save()
        return HttpResponseRedirect(reverse('polls:q_page', args=[id]))


def nvote(request, id):
    ip_req = request.META.get('HTTP_X_FORWARDED_FOR', request.META.get('REMOTE_ADDR', '')).split(',')[0].strip()

    q = get_object_or_404(Question, pk=id)
    vh = VoteHistory()
    if VoteHistory.objects.filter(question_id=q.id, ip=str(ip_req)) or VoteHistory.objects.filter(question_id=q.id, user=request.user.username):
        voted = True
        return render(request, 'polls/q_page.html', {
                'question': q,
                'error': 'شما قبلا رای دادید.',
            })
    else:
        voted = False
    try:
        if q.date_limit_checker() == 1 and not voted:
            if request.POST:
                q.n_votes += 1

                vh.question = q
                vh.user = request.user.username
                vh.ip = str(ip_req)
                vh.choice = '-'
            else:
                return render(request, 'polls/q_page.html', {
                    'question': q,
                    'error': 'خطا در ثبت رای !',
                })
        elif q.date_limit_checker() == 0:
            return render(request, 'polls/q_page.html', {
                    'question': q,
                    'error': 'این نظر سنجی دارای محدودیت زمانی است و هنوز شروع نشده!',
                })
        elif q.date_limit_checker() == 2:
            return render(request, 'polls/q_page.html', {
                    'question': q,
                    'error': 'این نظرسنجی دارای محدودیت زمانی بوده و مهلت آن به اتمام رسیده است.',
                })
        else:
            return HttpResponseRedirect(reverse('polls:q_page', args=[id]))
    except:
        return render(request, 'polls/q_page.html', {
            'question': q,
            'error': 'خطا در ثبت رای !',
        })
    else:
        q.save()
        vh.save()
        return HttpResponseRedirect(reverse('polls:q_page', args=[id]))


def signup(request):
    u = User()
    try:
        u.username = request.POST['username']
        u.email = request.POST['email']
        u.set_password(request.POST['password'])
        u.save()
        login(request, u)
    except:
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
    return render(request, 'polls/profile.html', {
        'user': u,
    })


def signin(request):
    user_name = request.POST['username']
    passwd = request.POST['password']
    user = authenticate(request, username=user_name, password=passwd)
    if user is not None:
        login(request, user)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


def signout(request):
    logout(request)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


@login_required
def profile(request):
    u = request.user

    client_ip, is_routable = get_client_ip(request)
    if client_ip is None:
        pass
    else:
        client_ip
    ip_req = request.META.get('HTTP_X_FORWARDED_FOR', request.META.get('REMOTE_ADDR', '')).split(',')[0].strip()

    vh = VoteHistory.objects.filter(user=u.username)

    return render(request, 'polls/profile.html', {
        'user': u,
        'vote_history': vh,
        'ip_ipware': client_ip,
        'ip_request': ip_req,
    })


@login_required
def change_pass(request):
    u = request.user
    old_pass = request.POST['old_pass']
    new_pass = request.POST['new_pass']
    re_pass = request.POST['re_pass']
    check_pass = u.check_password(old_pass)

    def check_new_pass_eq():
        if new_pass == re_pass:
            return True
        else:
            return False

    if check_pass and new_pass == re_pass and len(new_pass) > 5:
        u.set_password(new_pass)
        u.save()
        logout(request)
        return render(request, 'polls/profile.html', {
            'user': u,
            'success': 'رمز با موفقیت تغییر یافت'
        })
    elif not u.check_password(old_pass):
        return render(request, 'polls/profile.html', {
            'user': u,
            'error': 'رمز قدیمی وارد شده نا معتبر است',
        })
    elif check_pass and new_pass == re_pass and len(new_pass) < 5:
        return render(request, 'polls/profile.html', {
            'user': u,
            'error': 'رمز وارد شده باید حداقل 5 رقم باشد',
        })
    elif check_pass and not check_new_pass_eq():
        return render(request, 'polls/profile.html', {
            'user': u,
            'error': 'رمز جدید وارد شده برابر نیست'
        })
    elif old_pass == new_pass and new_pass == re_pass:
        return render(request, 'polls/profile.html', {
            'user': u,
            'error': 'رمز جدید نباید مانند رمز قدیمی باشد'
        })

    else:
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


def user_signing(request):
    if not request.user.is_authenticated:
        return render(request, 'polls/user-signing.html')
    else:
        return HttpResponseRedirect(reverse('polls:profile'))


def comment(request, id):
    cmnt = Comments()
    try:
        cmnt.user = request.user
        cmnt.text = request.POST['comment-inp']
        cmnt.question = get_object_or_404(Question, pk=id)
        cmnt.save()
    except:
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


@login_required
def add_q_page(request):
    u = request.user
    return render(request, 'polls/q_add.html', {
        'user': u,
    })

@login_required
def add_q(request):
    limit = 5
    u = request.user
    q = Question()
    try:
        q.user = request.user
        q.title = request.POST['title']
        q.text = request.POST['desc']
        q.publish = request.POST.get('publish', False)
        if request.POST['p_text']:
            q.p_text = request.POST['p_text']
        if request.POST['n_text']:
            q.n_text = request.POST['n_text']
    except:
        return render(request, 'polls/q_add.html', {
            'user': u,
            'error': 'مشکل در ثبت فرم',
        })
    if u.question_set.count() >= int(limit) and limit != 0:
        return render(request, 'polls/q_add.html', {
            'user': u,
            'error': 'شما مجاز به ساخت حداکثر %s فرم هستید.' % limit,
        })
    else:
        q.save()
        return HttpResponseRedirect(reverse('polls:q_page', args=[q.id]))


def tag(request, slug):

polls/templates/polls/comments.html
{% for cmnt in question.comments_set.all %}
    <div class="comment-box">
        <span class="float-left">
            <i class="fa fa-calendar"></i>&nbsp;
            {{ cmnt.jalali_date.full }}
            ساعت&nbsp;
            {{ cmnt.date.time }}
        </span>
        <span class="float-right">
            <a href="{% url 'polls:user-poll' cmnt.user %}"><i class="fa fa-user"></i>&nbsp;
            {{ cmnt.user }}
            </a>
        </span>
        <div class="clearfix"></div>
        <p>
            {{ cmnt.text|linebreaks }}
        </p>
        <div class="clearfix"></div>
    </div>
{% empty %}
    هیچ نظری یافت نشد.<br>
{% endfor %}

<hr>

{% if request.user.is_authenticated %}
    <form action="{% url 'polls:comment' question.id%}" method="POST">
    {% csrf_token %}
        <textarea id="comment-inp" name="comment-inp" placeholder="نظر خود را بنویسید ..." required></textarea>
        <button type="submit" class="btn btn-warning btn-block hand">ارسال نظر</button>
    </form>
    {% else %}
    <div class="alert alert-primary alert-dismissible text-center">
        برای نظر دادن باید وارد حساب کاربری شوید <br>
        <button type="button" class="btn btn-light hand" data-toggle="modal" data-target="#myModal">
            <i class="fa fa-user"></i>&nbsp; ورود / ثبت نام
        </button>
    </div>
{% endif %}

polls/templates/polls/form-management.html
{% extends 'polls/base.html' %}
{% block title %}
{{ user.username }} - مدیریت فرم ها
{% endblock %}

{% block content %}
<div class="jumbotron text-center">
    <h3>    مدیریت فرم های کاربر   : {{ user.username }} &nbsp;<span class="badge badge-danger">{{ user.question_set.count }}</span>    </h3>
</div>

{% if error %}
<div class="alert alert-danger alert-dismissible text-center">
    <button type="button" class="close hand" data-dismiss="alert">&times;</button>
    <strong>خطا !</strong><br> {{ error }}
</div>
{% elif success %}
<div class="alert alert-success alert-dismissible text-center">
    <button type="button" class="close hand" data-dismiss="alert">&times;</button>
    {{ success }}
</div>
{% endif %}

<section class="section-post no-hand">

    {% for question in user.question_set.all %}
    <a href="{{ question.get_absolute_url }}">{{ question.title|truncatewords:22 }}</a>
    <span class="float-left">

    {% if question.publish %}
        <i class="fa fa-eye text-success"></i>
    {% else %}
        <i class="fa fa-eye-slash text-danger"></i>
    {% endif %}

    &nbsp;

    <span class="badge badge-dark">{{ question.sum_votes }}</span>

    <a href="{% url 'polls:edit-form-page' question.id %}" class="btn btn-success btn-sm form-management-btn"><i class="fa fa-pencil"></i>&nbsp; ویرایش</a>
    <button type="button" class="btn btn-danger btn-sm form-management-btn hand" data-toggle="modal" data-target="#delete-alert{{ question.id }}">
        <i class="fa fa-eraser"></i>&nbsp; پاک کردن
    </button>
    {% include 'polls/delete-modal.html' %}
    </span>
    <div class="clearfix"></div>
    <hr>

    {% empty %}
        <div class="text-center">
            <h3>    شما هیچ فرمی نساخته اید.    </h3><br>
            <a href="{% url 'polls:add_q_page' %}" class="btn btn-success tag-btn"><i class="fa fa-plus"></i>&nbsp;   فرم جدید بسازید    </a><br>
            <a href="{% url 'polls:index' %}" class="btn btn-danger tag-btn"><i class="fa fa-home"></i>&nbsp;   رفتن به صفحه اصلی    </a>
        </div>

    {% endfor%}
</section>

{% endblock%}

polls/templates/polls/nav.html
<div id="top-nav" class="bg-dark">
        <span class="float-right">
            <a href="{% url 'polls:index' %}" class="btn btn-light btn-sm"><i class="fa fa-home"></i></a>
        </span>

    {% if request.user.is_authenticated %}
        <span class="float-right top-nav-right">
            <div class="dropdown">
                <button type="button" class="btn btn-light btn-sm dropdown-toggle hand" data-toggle="dropdown">
                    <i class="fa fa-user"></i>&nbsp;   
                    {% if request.user.get_full_name %}
                        {{ request.user.get_full_name }}
                    {% else %}
                        {{ request.user.username }}
                    {% endif %}
                </button>
                <div class="dropdown-menu">
                    <h5 class="dropdown-header">    خوش آمدید   {{ request.user.username }}   </h5>
                    <a class="dropdown-item" href="{% url 'polls:profile' %}">    پروفایل کاربر   </a>
                    <a class="dropdown-item" href="{% url 'polls:profile' %}#profile-chpass">  تغییر رمز عبور  </a>
                    <a class="dropdown-item" href="{% url 'polls:logout' %}"><i class="fa fa-sign-out"></i>&nbsp;   خروج</a>
                </div>
            </div>
        </span>

        <span class="float-left ltr">
            <div class="dropdown">
                <button type="button" class="btn btn-warning btn-sm dropdown-toggle hand" data-toggle="dropdown">
                  <i class="fa fa-edit"></i>
                </button>
                <div class="dropdown-menu rtl">
                    <h5 class="dropdown-header">ابزار نظرسنجی</h5>
                    <a class="dropdown-item bg-warning" href="{% url 'polls:add_q_page' %}"><i class="fa fa-plus"></i>&nbsp; فرم جدید </a>
                    <a class="dropdown-item" href="{% url 'polls:form-management' %}">مدیریت فرم ها</a>
                    <a class="dropdown-item" href="#">راهنما</a>
                </div>
            </div>
        </span>

    {% else %}
        <span class="float-right top-nav-right">
            <button type="button" class="btn btn-warning hand btn-sm" data-toggle="modal" data-target="#myModal">
                <i class="fa fa-user"></i>&nbsp; ورود/ عضویت
            </button>
        </span>
        {% include 'polls/user-signing-modal.html' %}

    {% endif %}

    <div class="clearfix"></div>

</div>

polls/templates/polls/signup.html
<!-- The Modal -->
<div class="modal fade" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">
    
        <!-- Modal Header -->
        <div class="modal-header">
            <h4 class="modal-title">ورود / عضویت</h4>
            <button type="button" class="close hand" data-dismiss="modal">&times;</button>
        </div>
    
        <!-- Modal body -->
        <div class="modal-body">
                    <!-- Nav tabs -->
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a class="nav-link active" data-toggle="tab" href="#modal-signin">ورود کاربر</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#modal-signup">ثبت نام</a>
                </li>
            </ul>
            
            <!-- Tab panes -->
            <div class="tab-content">
            <div class="tab-pane container active" id="modal-signin">
                <form action="{% url 'polls:login' %}" method="POST">
                    {% csrf_token %}
                    <input type="text" class="full-width ltr top-margin-5" class="ltr" id="username" name="username" placeholder="نام کاربری"><br>
                    <input type="password" class="full-width ltr top-margin-5" class="ltr" id="password" name="password" placeholder="رمز"><br>
                    <button type="submit" class="btn btn-dark btn-block hand top-margin-5"><i class="fa fa-sign-in fa-rotate-180"></i>&nbsp; ورود</button>
                </form>
                <hr>
                <a href="#" class="">رمز عبور خود را فراموش کردید؟</a>
            </div>
            <div class="tab-pane container fade" id="modal-signup">
                <form action="{% url 'polls:signup' %}" method="POST">
                    {% csrf_token %}
                    <input type="text" class="full-width ltr top-margin-5" name="username" id="signup_username" placeholder="نام کاربری" required><br>
                    <input type="email" class="full-width ltr top-margin-5" name="email" id="signup_email" placeholder="ایمیل" required><br>
                    <input type="password" class="full-width ltr top-margin-5" name="password" id="signup_pass" placeholder="رمز عبور" required><br>
                    <button type="submit" class="btn btn-warning btn-block hand top-margin-5"><i class="fa fa-user-plus"></i>&nbsp;   ثبت نام</button>
                </form>
            </div>
            </div>
        </div>








        <!-- Modal footer   ******
        <div class="modal-footer">
            <button type="button" class="btn btn-danger btn-sm hand" data-dismiss="modal">بستن</button>
        </div>
        *****   -->
        </div>
    </div>
</div>

polls/templates/polls/tab-pane.html
<div class="container"><br>
    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
        <li class="nav-item">
        <a class="nav-link active" data-toggle="tab" href="#tab-page-1">
            توضیحات
        </a>
        </li>
        <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#tab-page-2">
            نظرات   &nbsp;<span class="badge badge-primary">{{ question.comments_set.count }}</span>
        </a>
        </li>
    </ul>
    
    <!-- Tab panes -->
    <div class="tab-content">

        <div id="tab-page-1" class="container tab-pane active"><br>

            <p><a href="{% url 'polls:user-poll' question.user %}"> <i class="fa fa-user"></i>&nbsp; {{ question.user.username }}</a></p>

            <h4>
                <i class="fa fa-list-alt"></i> &nbsp;    توضیحات بیشتر
            </h4>
            <p>
                {% if question.text %}
                    {{ question.text|linebreaks }}
                {% else %}
                توضیحاتی وجود ندارد ...
                {% endif %}
            </p><hr>
            <h4>
                <i class="fa fa-warning text-danger"></i> &nbsp;    محدودیت ها
            </h4>
            <p>
                {% if question.date_limit_checker is 0 %}
                <i class="fa fa-clock-o"></i> &nbsp;    محدودیت زمانی : <span class="text-danger"> دارد </span><br>
                <i class="text-info fa fa-info"></i> &nbsp;       وضعیت : <span class="text-primary"> هنوز آغاز نشده است. </span><br>
                <i class="text-info fa fa-hourglass-start"></i> &nbsp;    زمان شروع : <span class="text-primary">
                    {{ question.fa_start_date.full }} - ساعت 
                    {{ question.start_date.time }}
                </span><br>
                <i class="text-info fa fa-hourglass-end"></i> &nbsp;       زمان پایان : <span class="text-primary">
                    {{ question.fa_end_date.full }} - ساعت 
                    {{ question.end_date.time }}
                </span>
        
                {% elif question.date_limit_checker is 1 %}
                    <i class="fa fa-clock-o"></i> &nbsp;    محدودیت زمانی : <span class="text-danger"> دارد </span><br>
                    <i class="text-success fa fa-info"></i> &nbsp;   وضعیت : <span class="text-success">     فعال    </span><br>
                    <i class="text-success fa fa-hourglass-start"></i> &nbsp;    زمان شروع : <span class="text-primary">
                        {{ question.fa_start_date.full }} - ساعت 
                        {{ question.start_date.time }}
                    </span><br>
                    <i class="text-success fa fa-hourglass-end"></i> &nbsp;   زمان پایان : <span class="text-primary">
                        {{ question.fa_end_date.full }} - ساعت 
                        {{ question.end_date.time }}
                    </span>
        
                {% elif question.date_limit_checker is 2 %}
                    <i class="fa fa-clock-o"></i> &nbsp;    محدودیت زمانی : <span class="text-danger"> دارد </span><br>
                    <i class="text-danger fa fa-info"></i> &nbsp;    وضعیت : <span class="text-danger">    به پایان رسیده    </span><br>
                    <i class="text-danger fa fa-hourglass-start"></i> &nbsp;    زمان شروع : <span class="text-primary">
                        {{ question.fa_start_date.full }} - ساعت 
                        {{ question.start_date.time }}
                    </span><br>
                    <i class="text-danger fa fa-hourglass-end"></i> &nbsp;    زمان پایان : <span class="text-primary">
                        {{ question.fa_end_date.full }} - ساعت 
                        {{ question.end_date.time }}
                    </span>
                {% else %}
                <i class="fa fa-clock-o"></i> &nbsp;    محدودیت زمانی : <span class="text-success"> ندارد </span><br>
                <i class="text-success fa fa-info"></i> &nbsp;   وضعیت : <span class="text-success">     فعال    </span><br>
                {% endif %}
            </p>
    
        </div>

        <div id="tab-page-2" class="container tab-pane fade"><br>
            {% include 'polls/comments.html' %}
        </div>


    </div>
</div>