core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    path('edit-form-<int:id>/', views.edit_form, name='edit-form'),
    path('form-<int:id>/edit/', views.edit_form_page, name='edit-form-page'),
    path('delete-form-<int:id>/', views.delete_form, name='delete-form'),
    path('form-management/', views.form_management, name='form-management'),
    path('user/<str:user>/', views.user_poll, name='user-poll'),
    path('tags/', views.tags, name='tags'),
    path('tag/<slug:slug>/', views.tag, name='tag'),
    path('addq/', views.add_q, name="add_q"),
    path('add-a-form/', views.add_q_page, name='add_q_page'),
    path('comment-<int:id>/', views.comment, name='comment'),
    path('profile/', views.profile, name='profile'),
    path('change-password/', views.change_pass, name='change_pass'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.signout, name='logout'),
    path('login/', views.signin, name='login'),
    path('user-signing/', views.user_signing, name="user-signing"),
    path('pvote/<int:id>/', views.pvote, name='pvote'),
    path('nvote/<int:id>/', views.nvote, name='nvote'),
    path('form-<int:id>/', views.q_page, name='q_page'),
    path('index/', views.index, name='index'),
    path('', views.intro, name='intro'),
]

polls/models.py
from django.db import models
from django.utils import timezone
import datetime
from .jalali_date_conv import shamsiDate
from django.contrib.auth.models import User
from django.utils.text import slugify

# Create your models here.


class Tag(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)

    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        return '/tag/%s/' % slugify(self.slug)


class Question(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=250, verbose_name='Title')
    text = models.TextField(verbose_name='Description', blank=True, null=True)
    date = models.DateTimeField(default=timezone.now, verbose_name='Date', blank=True)
    date_created = models.DateTimeField(auto_now_add=timezone.now())
    date_modified = models.DateTimeField(auto_now=timezone.now())
    publish = models.BooleanField(default=True, verbose_name='Publish')
    p_text = models.CharField(max_length=200, default='موافقم', verbose_name='Positive choice text', blank=True, null=True)
    p_votes = models.IntegerField(default=0, verbose_name='Positive choice votes', blank=True, null=True)
    n_text = models.CharField(max_length=200, default='مخالفم', verbose_name='Negative choice text', blank=True, null=True)
    n_votes = models.IntegerField(default=0, verbose_name='Negative choice votes', blank=True, null=True)
    date_limit = models.BooleanField(default=False)
    start_date = models.DateTimeField(blank=True, null=True)
    end_date = models.DateTimeField(blank=True, null=True)
    tags = models.ManyToManyField(Tag)

    class Meta:
        ordering = ['-date_created']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return '/form-%s/' % self.id

    def jalali_date(self):
        gdate = self.date
        return shamsiDate(gdate.year, gdate.month, gdate.day)

    def p_percent(self):
        sum = self.p_votes + self.n_votes
        if self.p_votes == 0 and self.n_votes == 0:
            percent = 50
        if self.p_votes == 0:
            percent = 0
        else:
            percent = (self.p_votes * 100)/sum
        return percent

    def n_percent(self):
        sum = self.n_votes + self.p_votes
        if self.p_votes == 0 and self.n_votes == 0:
            percent = 50
        if self.n_votes == 0:
            percent = 0
        else:
            percent = (self.n_votes * 100)/sum
        return percent

    def date_limit_checker(self):
        if self.date_limit:
            if timezone.now() < self.start_date < self.end_date:
                return 0
            elif self.start_date < timezone.now() < self.end_date:
                return 1
            elif self.start_date < self.end_date < timezone.now():
                return 2
            else:
                return False
        else:
            return True

    def fa_start_date(self):
        gdate = self.start_date
        return shamsiDate(gdate.year, gdate.month, gdate.day)

    def fa_end_date(self):
        gdate = self.end_date
        return shamsiDate(gdate.year, gdate.month, gdate.day)

    def sum_votes(self):
        return self.p_votes + self.n_votes


class VoteHistory(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=timezone.now(), verbose_name='date')
    user = models.CharField(max_length=150, verbose_name='username')
    ip = models.CharField(max_length=50, verbose_name='voted ip')
    choice = models.CharField(max_length=50, verbose_name='choice')

    class Meta:
        ordering = ['-date']

    def __str__(self):
        return str(self.user) + ' ' + str(self.ip)


class Comments(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    text = models.TextField(blank=False, null=False)
    date = models.DateTimeField(auto_now_add=timezone.now())

    class Meta:
        ordering = ['-date']

    def __str__(self):
        return self.text

    def jalali_date(self):
        gdate = self.date
        return shamsiDate(gdate.year, gdate.month, gdate.day)

polls/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.http import Http404, HttpResponseRedirect
from .models import *
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from ipware import get_client_ip

# Create your views here.


def index(request):
    questions = Question.objects.all().filter(publish=True).order_by('-date')
    return render(request, 'polls/index.html', {
        'questions': questions,
        })


def q_page(request, id):
    ip_req = request.META.get('HTTP_X_FORWARDED_FOR', request.META.get('REMOTE_ADDR', '')).split(',')[0].strip()

    question = get_object_or_404(Question, pk=id)
    u = request.user
    vh = VoteHistory()
    if VoteHistory.objects.filter(question_id=question.id, ip=str(ip_req)) or VoteHistory.objects.filter(question_id=question.id, user=u.username):
        voted = True
    else:
        voted = False

    if u == question.user:
        user_is_same = True
    else:
        user_is_same = False

    if question.publish:
        return render(request, 'polls/q_page.html', {
            'question': question,
            'user_is_same': user_is_same,
            'voted': voted,
            })
    elif not question.publish and user_is_same:
        return render(request, 'polls/q_page.html', {
            'question': question,
            'user_is_same': user_is_same,
            'voted': voted,
            'not_pub_err': 'این فرم در وضعیت عدم انتشار است. در این حالت فرم شما به نمایش عموم در نمی آید وتنها خودتان میتوانید این فرم نظرسنجی را مشاهده کنید.',
            })
    else:
        return render(request, 'polls/404.html')


def pvote(request, id):
    ip_req = request.META.get('HTTP_X_FORWARDED_FOR', request.META.get('REMOTE_ADDR', '')).split(',')[0].strip()

    q = get_object_or_404(Question, pk=id)
    vh = VoteHistory()
    if VoteHistory.objects.filter(question_id=q.id, ip=str(ip_req)) or VoteHistory.objects.filter(question_id=q.id, user=request.user.username):
        voted = True
        return render(request, 'polls/q_page.html', {
                'question': q,
                'error': 'شما قبلا رای دادید.',
            })
    else:
        voted = False
    try:
        if q.date_limit_checker() == 1 and not voted:
            if request.POST:
                q.p_votes += 1

                vh.question = q
                vh.user = request.user.username
                vh.ip = str(ip_req)
                vh.choice = '+'

            else:
                return render(request, 'polls/q_page.html', {
                    'question': q,
                    'error': 'خطا در ثبت رای !',
                })
        elif q.date_limit_checker() == 0:
            return render(request, 'polls/q_page.html', {
                    'question': q,
                    'error': 'این نظر سنجی دارای محدودیت زمانی است و هنوز شروع نشده!',
                })
        elif q.date_limit_checker() == 2:
            return render(request, 'polls/q_page.html', {
                    'question': q,
                    'error': 'این نظرسنجی دارای محدودیت زمانی بوده و مهلت آن به اتمام رسیده است.',
                })
        else:
            return HttpResponseRedirect(reverse('polls:q_page', args=[id]))
    except:
        return render(request, 'polls/q_page.html', {
            'question': q,
            'error': 'خطا در ثبت رای !',
        })
    else:
        q.save()
        vh.save()
        return HttpResponseRedirect(reverse('polls:q_page', args=[id]))


def nvote(request, id):
    ip_req = request.META.get('HTTP_X_FORWARDED_FOR', request.META.get('REMOTE_ADDR', '')).split(',')[0].strip()

    q = get_object_or_404(Question, pk=id)
    vh = VoteHistory()
    if VoteHistory.objects.filter(question_id=q.id, ip=str(ip_req)) or VoteHistory.objects.filter(question_id=q.id, user=request.user.username):
        voted = True
        return render(request, 'polls/q_page.html', {
                'question': q,
                'error': 'شما قبلا رای دادید.',
            })
    else:
        voted = False
    try:
        if q.date_limit_checker() == 1 and not voted:
            if request.POST:
                q.n_votes += 1

                vh.question = q
                vh.user = request.user.username
                vh.ip = str(ip_req)
                vh.choice = '-'
            else:
                return render(request, 'polls/q_page.html', {
                    'question': q,
                    'error': 'خطا در ثبت رای !',
                })
        elif q.date_limit_checker() == 0:
            return render(request, 'polls/q_page.html', {
                    'question': q,
                    'error': 'این نظر سنجی دارای محدودیت زمانی است و هنوز شروع نشده!',
                })
        elif q.date_limit_checker() == 2:
            return render(request, 'polls/q_page.html', {
                    'question': q,
                    'error': 'این نظرسنجی دارای محدودیت زمانی بوده و مهلت آن به اتمام رسیده است.',
                })
        else:
            return HttpResponseRedirect(reverse('polls:q_page', args=[id]))
    except:
        return render(request, 'polls/q_page.html', {
            'question': q,
            'error': 'خطا در ثبت رای !',
        })
    else:
        q.save()
        vh.save()
        return HttpResponseRedirect(reverse('polls:q_page', args=[id]))


def signup(request):
    u = User()
    try:
        u.username = request.POST['username']
        u.email = request.POST['email']
        u.set_password(request.POST['password'])
        u.save()
        login(request, u)
    except:
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
    return render(request, 'polls/profile.html', {
        'user': u,
    })


def signin(request):
    user_name = request.POST['username']
    passwd = request.POST['password']
    user = authenticate(request, username=user_name, password=passwd)
    if user is not None:
        login(request, user)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


def signout(request):
    logout(request)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


@login_required
def profile(request):
    u = request.user

    client_ip, is_routable = get_client_ip(request)
    if client_ip is None:
        pass
    else:
        client_ip
    ip_req = request.META.get('HTTP_X_FORWARDED_FOR', request.META.get('REMOTE_ADDR', '')).split(',')[0].strip()

    vh = VoteHistory.objects.filter(user=u.username)

    return render(request, 'polls/profile.html', {
        'user': u,
        'vote_history': vh,
        'ip_ipware': client_ip,
        'ip_request': ip_req,
    })


@login_required
def change_pass(request):
    u = request.user
    old_pass = request.POST['old_pass']
    new_pass = request.POST['new_pass']
    re_pass = request.POST['re_pass']
    check_pass = u.check_password(old_pass)

    def check_new_pass_eq():
        if new_pass == re_pass:
            return True
        else:
            return False

    if check_pass and new_pass == re_pass and len(new_pass) > 5:
        u.set_password(new_pass)
        u.save()
        logout(request)
        return render(request, 'polls/profile.html', {
            'user': u,
            'success': 'رمز با موفقیت تغییر یافت'
        })
    elif not u.check_password(old_pass):
        return render(request, 'polls/profile.html', {
            'user': u,
            'error': 'رمز قدیمی وارد شده نا معتبر است',
        })
    elif check_pass and new_pass == re_pass and len(new_pass) < 5:
        return render(request, 'polls/profile.html', {
            'user': u,
            'error': 'رمز وارد شده باید حداقل 5 رقم باشد',
        })
    elif check_pass and not check_new_pass_eq():
        return render(request, 'polls/profile.html', {
            'user': u,
            'error': 'رمز جدید وارد شده برابر نیست'
        })
    elif old_pass == new_pass and new_pass == re_pass:
        return render(request, 'polls/profile.html', {
            'user': u,
            'error': 'رمز جدید نباید مانند رمز قدیمی باشد'
        })

    else:
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


def user_signing(request):
    if not request.user.is_authenticated:
        return render(request, 'polls/user-signing.html')
    else:
        return HttpResponseRedirect(reverse('polls:profile'))


def comment(request, id):
    cmnt = Comments()
    try:
        cmnt.user = request.user
        cmnt.text = request.POST['comment-inp']
        cmnt.question = get_object_or_404(Question, pk=id)
        cmnt.save()
    except:
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


@login_required
def add_q_page(request):
    u = request.user
    return render(request, 'polls/q_add.html', {
        'user': u,
    })

@login_required
def add_q(request):
    limit = 5
    u = request.user
    q = Question()
    try:
        q.user = request.user
        q.title = request.POST['title']
        q.text = request.POST['desc']
        q.publish = request.POST.get('publish', False)
        if request.POST['p_text']:
            q.p_text = request.POST['p_text']
        if request.POST['n_text']:
            q.n_text = request.POST['n_text']
    except:
        return render(request, 'polls/q_add.html', {
            'user': u,
            'error': 'مشکل در ثبت فرم',
        })
    if u.question_set.count() >= int(limit) and limit != 0:
        return render(request, 'polls/q_add.html', {
            'user': u,
            'error': 'شما مجاز به ساخت حداکثر %s فرم هستید.' % limit,
        })
    else:
        q.save()
        return HttpResponseRedirect(reverse('polls:q_page', args=[q.id]))


def tag(request, slug):

polls/templates/intro/first_section.html
<div id="demo" class="carousel slide" data-ride="carousel">

        <!-- Indicators -->
        <ul class="carousel-indicators hand">
          <li data-target="#demo" data-slide-to="0" class="active"></li>
          <li data-target="#demo" data-slide-to="1"></li>
          <li data-target="#demo" data-slide-to="2"></li>
        </ul>
        
        <!-- The slideshow -->
        <div class="carousel-inner">

            <div class="carousel-item active">
                <div class="container">
                    <h1>
                        آیا شما هم مثل من فکر میکنید؟
                    </h1>
                    <div class="row">
                        <div class="col-md-6">
                            <a href="#guide" class="btt btt-transparent">راهنما</a>
                        </div>
                        <div class="col-md-6">
                            <a href="{% url 'polls:user-signing' %}" class="btt btt-blue">ورود / ثبت نام</a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="carousel-item">
                <div class="container">
                    <h1>
                        آیا شما هم مثل من فکر میکنید؟
                    </h1>
                    <div class="row">
                        <div class="col-md-12">
                            <a href="{% url 'polls:index' %}" class="btt btt-blue">لیست فرم ها</a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="carousel-item">
                    <div class="container">
                        <h1>
                            آیا شما هم مثل من فکر میکنید؟
                        </h1>
                        <div class="row">
                            <div class="col-md-12">
                                <a href="https://github.com/iamrf/doyouthinklikeme" class="btt btt-transparent">
                                    <i class="fa fa-github fa-2x"></i> &nbsp; مشارکت در این پروژه
                                </a>
                            </div>
                        </div>
                    </div>
            </div>
        </div>
        
        <!-- Left and right controls -->
        <a class="carousel-control-prev" href="#demo" data-slide="prev">
          <span class="carousel-control-next-icon"></span>
        </a>
        <a class="carousel-control-next" href="#demo" data-slide="next">
          <span class="carousel-control-prev-icon"></span>
        </a>
      </div>
      

polls/templates/intro/fourth_section.html
<div class="container">

    <div class="row">
        <div id="contact-form" class="col-md-6 col-lg-4 text-center text-light">

            <h2 class="h2-title">فرم تماس با ما</h2>
            <form action="" method="POST">
                {% csrf_token %}
                <input type="text" name="" id="" class="form-control form-element" placeholder="نام شما">
                <input type="email" name="" id="" class="form-control form-element ltr" placeholder="آدرس ایمیل">
                <textarea name="" id="" class="form-control form-element" placeholder="متن پیام"></textarea>
                <button type="submit" class="btn btn-block btn-light hand">ارسال</button>
            </form>

        </div>
        <div id="" class="col text-center text-light">

            <h2 class="h2-title">
                ما را دنبال کنید
            </h2>
            <div class="row">
                <div class="col-lg-2 col-md-4 col-sm-4">
                    <a href="mailto:info@doyouthinklikeme.ir" class="footer-icon">
                    <i class="fa fa-envelope-o fa-2x"></i><br> ایمیل
                    </a>
                </div>
                <div class="col-lg-2 col-md-4 col-sm-4">
                    <a href="tel:09368489724" class="footer-icon">
                        <i class="fa fa-phone fa-2x"></i><br> تلفن
                    </a>
                </div>
                <div class="col-lg-2 col-md-4 col-sm-4">
                    <a href="#" class="footer-icon">
                        <i class="fa fa-envelope fa-2x"></i><br> پیامک
                    </a>
                </div>
                <div class="col-lg-2 col-md-4 col-sm-4">
                    <a href="https://instagram.com/doyouthinklikeme" class="footer-icon">
                        <i class="fa fa-instagram fa-2x"></i><br>اینستاگرام
                    </a>
                </div>
                <div class="col-lg-2 col-md-4 col-sm-4">
                    <a href="" class="footer-icon">
                        <i class="fa fa-creative-commons fa-2x"></i><br> گواهینامه نرم افزار آزاد
                    </a>
                </div>
                <div class="col-lg-2 col-md-4 col-sm-4">
                    <a href="https://github.com/iamrf/doyouthinklikeme" class="footer-icon">
                        <i class="fa fa-github fa-2x"></i><br> سورس پروژه
                    </a>
                </div>
            </div>
            <hr>
            
            <p class="text-right">
                <strong>شما هم مثل من فکر میکنید</strong> یک برنامه منبع باز است. از مشارکت شما در این پروژه استقبال میکنیم.
                <a href="https://github.com/iamrf/doyouthinklikeme" class="btn btn-light">لینک پروژه</a>
            </p>
            <p class="text-right">
                <i class="fa fa-copyright"></i> کلیه حقوق این برنامه متعلق به <strong><a href="https://iamrf.net/" target="_blank" class="text-light">iamrf</a></strong> است.
            </p>

        </div>



    </div>
</div>

polls/templates/intro/header.html
<div class="scroll-header">
    <div class="progress" style="height:.2rem">
        <div class="progress-bar bg-warning" id="scroll-indicator"></div>
    </div>
</div>


<nav id="top-nav" class="bg-gradient navbar navbar-expand-md navbar-dark">
    <!-- Brand -->
    <a class="navbar-brand" href="{% url 'polls:intro' %}">    شما هم مثل من فکر میکنید؟     </a>
    
    <!-- Toggler/collapsibe Button -->
    <button class="navbar-toggler hand" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>
    
    <!-- Navbar links -->
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav">
            <li class="nav-item">
                {% if request.user.is_authenticated %}
                <a class="nav-link" href="{% url 'polls:profile' %}"><i class="fa fa-user"></i> &nbsp; پروفایل {{user.username }}</a>
                {% else %}
                <a class="nav-link" href="{% url 'polls:user-signing' %}"><i class="fa fa-user"></i> &nbsp; ورود/ عضویت</a>
                {% endif %}
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#guide">راهنما</a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'polls:logout' %}"><i class="fa fa-sign-out"></i>&nbsp;   خروج</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav> 

polls/templates/intro/index.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="theme-color" content="#fff"/>
        <title>{% block title %}آیا شما هم مثل من فکر میکنید؟{% endblock %}</title>
        <link rel="stylesheet" type="text/css" href="{% static 'intro/css/style.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'intro/css/bootstrap.css' %}">
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <![endif]-->
        <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <script src="{% static 'intro/js/script.js' %}"></script>
        {% block script %}{% endblock %}
    </head>
    <body>
        <header>
            {% include 'intro/header.html' %}
        </header>

        <div class="clearfix"></div>
        
        <section id="first-section" class="section-fit-page">
            {% include 'intro/first_section.html' %}
        </section>

        <div class="clearfix"></div>

        <section id="guide" class="">
            {% include 'intro/second_section.html' %}
        </section>

        <div class="clearfix"></div>

        <section id="third-section" class="">
            {% include 'intro/third_section.html' %}
        </section>

        <div class="clearfix"></div>

        <section id="contact-section" class="">
            {% include 'intro/fourth_section.html' %}
        </section>

        <div class="clearfix"></div>

    </body>
</html>

polls/templates/intro/second_section.html
<div class="container">

    <h2 class="sec-title text-light bg-dark text-center">
        کمی بیشتر درباره 
        <strong>
            شما هم مثل من فکر میکنید؟
        </strong>
    </h2>

    <div class="clearfix"></div>
    <br>

    <div class="row">
        <div class="col-md-12 text-dark">
            <i class="fa fa-star"></i>&nbsp; این یک نمونه فرم نظرسنجی است:
            <div class="card">
                <div class="card-body">
                    <h2 class="text-dark">
                        {{ question.title }}
                    </h2>
                    {% include 'polls/progress_full.html' %}
                    <br>
                    <p>
                            کره زمین، از یخ‌بندان‌های طولانی و اتفاقاتی بسیار سنگین‌تر از حضور انسان، جان سالم به در برده است. این ما هستیم که برای بقای خود روی کره زمین، تنها سیاره قابل سکونتی که می‌شناسیم باید تلاش کنیم. یادمان باشد که بقای زمین در گروی بقای ما نیست بلکه بقای ما وابسته به زمین است ...
                    <br><a href="http://earthsoldier.ir/p/earthday2015/" target="_blank" referrerpolicy="no-referrer">منبع : داریم زمین را از دست می‌دهیم!</a>
                    </p>
                    <a href="{{ question.get_absolute_url }}" class="btn btn-outline-dark btn-block btn-lg"> رای دهید </a>

                    <br><hr>

                    <p>
                        <span class="text-dark">
                        -    میخواهید <strong>رای </strong> دهید؟
                        </span><br>
                        برای رای دادن لازم نیست ثبت نام کنید. هر آی پی میتواند تنها <strong>یک رای </strong> به هر سوال دهد. برای رای دادن میتوانید <strong><a href="{% url 'polls:index' %}">از اینجا</a> </strong> وارد لیست نظرسنجی های موجود شوید و یا مستقیما وارد صفحه هر سوال شوید.
                    </p>
                    <p>
                        <span class="text-dark">
                        -    میخواهید <strong>فرم نظرسنجی جدید</strong> بسازید؟
                        </span><br>
                        برای این کار ابتدا وارد حساب کاربری خود شده سپس از طریق دکمه ابزار نظرسنجی در قسمت بالای صفحه فرم جدید و دلخواه خود را بسازید.
                    </p>
                    <p>
                        <span class="text-dark">
                        -     میخواهید فرم خود را <strong>ویرایش</strong> کنید؟
                        </span><br>
                        ابزار "<strong>مدیریت و ویرایش فرم ها</strong>" در مسیر <strong>ابزار نظرسنجی > مدیریت فرم ها </strong>در دسترس است.
                    </p>
                </div>

            </div>
        </div>
    </div>


</div>

polls/templates/intro/sign-tab.html
<!-- Nav tabs -->
<ul class="nav nav-tabs">
        <li class="nav-item">
          <a class="nav-link active" data-toggle="tab" href="#home">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" data-toggle="tab" href="#menu1">Menu 1</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" data-toggle="tab" href="#menu2">Menu 2</a>
        </li>
      </ul>
      
      <!-- Tab panes -->
      <div class="tab-content">
        <div class="tab-pane container active" id="home">
                <form action="{% url 'polls:login' %}" method="POST">
                        {% csrf_token %}
                        <input type="text" class="form-control ltr form-element" id="username" name="username" placeholder="نام کاربری">
                        <input type="password" class="form-control ltr form-element" id="password" name="password" placeholder="رمز">
                        <button type="submit" class="btn btn-dark btn-block hand"><i class="fa fa-sign-in fa-rotate-180"></i>&nbsp; ورود</button>
                    </form>
        </div>
        <div class="tab-pane container fade" id="menu1">...</div>
        <div class="tab-pane container fade" id="menu2">...</div>
      </div>

polls/templates/intro/third_section.html
<div class="container">
    <h2 class="sec-title text-light bg-dark text-center">
        آخرین فرم های ثبت شده
    </h2>
</div>
<div class="container-fluid">
    <div class="row">
        {% for question in questions %}
        <div class="col-md-6 col-lg-4 last-forms fade">
            <div class="card bg-light">
                <div class="card-body">
                    <a href="{{ question.get_absolute_url }}" class="text-dark"><h4>{{ question.title|truncatewords:50 }}</h4></a><hr>
                    <p>
                        {% include 'polls/progress_full.html' %}
                    </p>
                    <p>
                        {{ question.text|truncatewords:50|linebreaks }}
                    </p>
                    <br>
                    <a href="{{ question.get_absolute_url }}" class="btn btn-block btn-dark btn-lg">
                        رای دهید
                    </a>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="col-md-12">
            <div class="card bg-light">
                <div class="card-body">
                    <h3>
                        هیچ فرمی موجود نیست
                    </h3>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    
</div>